//
// Created by kevin on 11/2/22.
//

#ifndef SEMANTIC_COSTMAP_PLUGIN__VISIBILITY_CONTROL_H_
#define SEMANTIC_COSTMAP_PLUGIN__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define SEMANTIC_COSTMAP_PLUGIN_EXPORT __attribute__((dllexport))
#define SEMANTIC_COSTMAP_PLUGIN_IMPORT __attribute__((dllimport))
#else
#define SEMANTIC_COSTMAP_PLUGIN_EXPORT __declspec(dllexport)
#define SEMANTIC_COSTMAP_PLUGIN_IMPORT __declspec(dllimport)
#endif
#ifdef SEMANTIC_COSTMAP_PLUGIN_BUILDING_LIBRARY
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC SEMANTIC_COSTMAP_PLUGIN_EXPORT
#else
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC SEMANTIC_COSTMAP_PLUGIN_IMPORT
#endif
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC_TYPE SEMANTIC_COSTMAP_PLUGIN_PUBLIC
#define ESEMANTIC_COSTMAP_PLUGIN_LOCAL
#else
#define SEMANTIC_COSTMAP_PLUGIN_EXPORT __attribute__((visibility("default")))
#define SEMANTIC_COSTMAP_PLUGIN_IMPORT
#if __GNUC__ >= 4
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC __attribute__((visibility("default")))
#define SEMANTIC_COSTMAP_PLUGIN_LOCAL __attribute__((visibility("hidden")))
#else
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC
#define SEMANTIC_COSTMAP_PLUGIN_LOCAL
#endif
#define SEMANTIC_COSTMAP_PLUGIN_PUBLIC_TYPE
#endif

#endif //SEMANTIC_COSTMAP_PLUGIN__VISIBILITY_CONTROL_H_