features:
  one:
    xmin: 5.0
    xmax: 6.0
    ymin: 1.0
    ymax: 7.0
    label: "ramp1"
    floor: "1"
  two:
    xmin: 1.0
    xmax: 2.0
    ymin: 1.0
    ymax: 2.0
    label: "ramp2"
    floor: "1"
  three:
    xmin: 2.0
    xmax: 3.0
    ymin: 1.0
    ymax: 2.0
    label: "ramp23"
    floor: "1"

destinations:
  d1:
    x: 0.0
    y: 0.0
    floor: "3"
    label: "Room 324"
  d2:
    x: 2.0
    y: 2.0
    floor: "1"
    label: "Room 111"
